### ISSUE TITLE
Add controls

### ISSUE THREAD

**Issue by mgbleichner** [abinjakob/nEEGlace#2]
Upon startup,

 it should be possible to specify how many trials should be averaged, i.e. when specifying "average over the last forty trials", the average should be about the last forty trials, and older trials should be forgotten. 

It should be possible to specify channel combinations i.e. plot the data for the average of channel 2+3, and subtract that form the average of channel 7 and 8.

**Comment by abinjakob** [comment]
**1. Setting the Number of Trials for Averaging**

You can now specify the number of trials to be averaged using the variable maxTrials. This variable determines the ERP calculation based on the latest maxTrials.



**2. Plotting the Average ERP of Selected Channels**

You can specify the channels to be averaged by setting the variable chan2sel. The ERP is then averaged across these channels. If chan2sel is left empty, individual ERPs for all channels will be plotted separately.

Additionally, if you want to subtract the average ERP of selected channels from certain other channels, include the channels to be used for subtraction in the variable chan2diff.
